### ISSUE TITLE
Processing frames

### ISSUE THREAD

**Issue by elyselam** [aldrake87/OpenCV-Traffic-Counter#1]
Hi Alex,
As I ran the blobDetection.py, I get a series of sums of each frames up to frame 258 and then it throws the following error:
"Processing frame  258
Found  13  vehicle contours.
Contour # 0 : pos=(x= 241 , y= 216 ) size=(w= 35 , h= 37 ) valid= True
Contour # 1 : pos=(x= 276 , y= 169 ) size=(w= 31 , h= 20 ) valid= True
Contour # 2 : pos=(x= 106 , y= 143 ) size=(w= 36 , h= 25 ) valid= True
Contour # 3 : pos=(x= 141 , y= 129 ) size=(w= 15 , h= 25 ) valid= False
Contour # 4 : pos=(x= 211 , y= 118 ) size=(w= 6 , h= 4 ) valid= False
Contour # 5 : pos=(x= 221 , y= 117 ) size=(w= 9 , h= 5 ) valid= False
Contour # 6 : pos=(x= 126 , y= 115 ) size=(w= 7 , h= 5 ) valid= False
Contour # 7 : pos=(x= 150 , y= 111 ) size=(w= 14 , h= 13 ) valid= False
Contour # 8 : pos=(x= 169 , y= 110 ) size=(w= 7 , h= 6 ) valid= False
Contour # 9 : pos=(x= 197 , y= 108 ) size=(w= 12 , h= 15 ) valid= False
Contour # 10 : pos=(x= 184 , y= 104 ) size=(w= 6 , h= 5 ) valid= False
Contour # 11 : pos=(x= 152 , y= 104 ) size=(w= 4 , h= 4 ) valid= False
Contour # 12 : pos=(x= 133 , y= 100 ) size=(w= 10 , h= 11 ) valid= False
**-- 13.2 seconds --
Traceback (most recent call last):
  File "blobDetection.py", line 463, in <module>
    cv2.line()
TypeError: Required argument 'img' (pos 1) not found**"

what does this mean? and how should we go about interpretting the results? If I just want to know how many cars appeared in the clip, do I just take (total # vehicle countours / total # of frames)?

Thank you!

**Comment by alex-drake** [comment]
Hi Elyse,

The error is due to running out frames in the video (looks like you are using one with 258 frames there) and so there isn't a frame 259 to use - it needs something to end the function without forcing an error but I have yet to add that in (haven't had the time to work on it, unfortunately). 

As for interpreting the results, I guess it depends on what you are wanting to do with it? I was using it to count the total number of vehicles moving across the threshold, in both directions, which should be displayed on the top of the video output. The console log you have provided also indicates how many blobs meet the threshold criteria per frame, so in that example you can see that 3 of the vehicle contours are valid (valid=True) and so will be passed to the blobs list as possible vehicles (and then checked using update_count() function). If you want to get the total number of vehicles then you may want to add an output for the variable total_cars (see line 450).

Hope that helps!
